Repository openscilab/xnum, pull requests merged in 2025-09, with the labels that each got.

#50 Double-Struck
  CHANGELOG.md
  README.md
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_gurmukhi.py
  tests/test_hindi.py
  tests/test_kannada.py
  tests/test_khmer.py
  tests/test_lao.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_telugu.py
  tests/test_thai.py
  tests/test_tibetan.py
  xnum/params.py
Labels: enhancement, numeral system

#52 Sans-Serif English Font Added
  CHANGELOG.md
  README.md
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_gurmukhi.py
  tests/test_hindi.py
  tests/test_kannada.py
  tests/test_khmer.py
  tests/test_lao.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_telugu.py
  tests/test_thai.py
  tests/test_tibetan.py
  xnum/params.py
Labels: enhancement, numeral system

#53 Monospace
  CHANGELOG.md
  README.md
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_gurmukhi.py
  tests/test_hindi.py
  tests/test_kannada.py
  tests/test_khmer.py
  tests/test_lao.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_telugu.py
  tests/test_thai.py
  tests/test_tibetan.py
  xnum/params.py
Labels: enhancement, numeral system

#54 Sans Serif Bold Mode for English Added
  CHANGELOG.md
  README.md
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_gurmukhi.py
  tests/test_hindi.py
  tests/test_kannada.py
  tests/test_khmer.py
  tests/test_lao.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_telugu.py
  tests/test_thai.py
  tests/test_tibetan.py
  xnum/params.py
Labels: enhancement, numeral system

#55 Version 0.6
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/publish_pypi.yml
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
  xnum/params.py
Labels: release

#66 Test
  CHANGELOG.md
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_gurmukhi.py
  tests/test_hindi.py
  tests/test_kannada.py
  tests/test_khmer.py
  tests/test_lao.py
  tests/test_limbu.py
  tests/test_mongolian.py
  tests/test_myanmar_shan.py
  tests/test_nko.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_sinhala_lith.py
  tests/test_telugu.py
  tests/test_thai.py
  tests/test_tibetan.py
Labels: test

#104 Test
  CHANGELOG.md
  tests/test_auto_and_edge_cases.py
Labels: test

#105 Version 0.8
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
  xnum/params.py
Labels: release
