Repository openscilab/xnum, pull requests merged in 2025-08, with the labels that each got.

#35 Odia
  CHANGELOG.md
  README.md
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_hindi.py
  tests/test_khmer.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_thai.py
  tests/test_tibetan.py
  xnum/params.py
Labels: enhancement, numeral system

#36 Minor edits
  AUTHORS.md
  CHANGELOG.md
  README.md
Labels: documentation

#37 Version 0.3
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
  xnum/params.py
Labels: release

#38 Telugu
  CHANGELOG.md
  README.md
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_hindi.py
  tests/test_khmer.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_telugu.py
  tests/test_thai.py
  tests/test_tibetan.py
  xnum/params.py
Labels: enhancement, numeral system

#39 Kannada
  CHANGELOG.md
  README.md
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_hindi.py
  tests/test_kannada.py
  tests/test_khmer.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_telugu.py
  tests/test_thai.py
  tests/test_tibetan.py
  xnum/params.py
Labels: numeral system

#42 Version 0.4
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
  xnum/params.py
Labels: release

#43 Lao
  CHANGELOG.md
  README.md
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_gurmukhi.py
  tests/test_hindi.py
  tests/test_kannada.py
  tests/test_khmer.py
  tests/test_lao.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_telugu.py
  tests/test_thai.py
  tests/test_tibetan.py
  xnum/params.py
Labels: numeral system

#45 Test
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_gurmukhi.py
  tests/test_hindi.py
  tests/test_kannada.py
  tests/test_khmer.py
  tests/test_lao.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_telugu.py
  tests/test_thai.py
  tests/test_tibetan.py
Labels: test

#46 English Fullwidth
  CHANGELOG.md
  README.md
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_gurmukhi.py
  tests/test_hindi.py
  tests/test_kannada.py
  tests/test_khmer.py
  tests/test_lao.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_telugu.py
  tests/test_thai.py
  tests/test_tibetan.py
  xnum/params.py
Labels: numeral system

#47 English Subscript
  CHANGELOG.md
  README.md
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_gurmukhi.py
  tests/test_hindi.py
  tests/test_kannada.py
  tests/test_khmer.py
  tests/test_lao.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_telugu.py
  tests/test_thai.py
  tests/test_tibetan.py
  xnum/params.py
Labels: numeral system

#48 English Superscript
  CHANGELOG.md
  README.md
  tests/test_arabic_indic.py
  tests/test_bengali.py
  tests/test_burmese.py
  tests/test_english.py
  tests/test_gujarati.py
  tests/test_gurmukhi.py
  tests/test_hindi.py
  tests/test_kannada.py
  tests/test_khmer.py
  tests/test_lao.py
  tests/test_odia.py
  tests/test_persian.py
  tests/test_telugu.py
  tests/test_thai.py
  tests/test_tibetan.py
  xnum/params.py
Labels: numeral system

#49 Version 0.5
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
  xnum/params.py
Labels: release
